version: '3.8'
services:
  api:
    image: ${DOCKER_REGISTRY}/${IMAGE_NAME}:dev-${BUILD_NUMBER}
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - DEBUG=true
      - PORT=8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
