version: '3.8'
services:
  api:
    image: ${DOCKER_REGISTRY}/${IMAGE_NAME}:prod-${BUILD_NUMBER}
    ports:
      - "80:8000"
    environment:
      - ENV=production
      - DEBUG=false
      - PORT=8000
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
